apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: kaniko-task
spec:
  params:
    - name: IMAGE
      type: string
    - name: DOCKERFILE
      type: string
    - name: CONTEXT
      type: string
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:latest
      volumeMounts:
      - name: acr-credentials
        mountPath: /kaniko/.docker
      command:
        - /kaniko/executor
      args:
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(params.CONTEXT)
        - --destination=$(params.IMAGE)
  volumes:
    - name: acr-credentials
      secret:
        secretName: acr-credentials
        items:
          - key: .dockerconfigjson
            path: config.json