apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pipeline-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data  # Adjust this path based on your host's file system
