apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pipeline-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual  # Ensure this matches your PV's storageClassName or is set for dynamic provisioning